backend:
  name: github
  repo: keep-network/website
  site_domain: keep.network
  base_url: https://backend.keep.network/
  auth_endpoint: netlify/auth
  open_authoring: true

site_url: https://keep.network

publish_mode: editorial_workflow

media_folder: static/images
public_folder: /images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "home-page",
            }
          - { label: "Path", name: "path", widget: "hidden", default: "/" }
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "markdown", minimal: true}
              - {label: "Body", name: "body", widget: "markdown", required: false}
              - {
                  label: "Background Image",
                  name: "bg_image",
                  widget: "image",
                  hint: "IMPORTANT! Image must be named \"hero-bg.jpg\" exactly
                    (it also must be a jpg), otherwise it will not appear.
                    Minimum image width of 2880px required (to be rendered as
                    1440px) to support higher resolution screens.",
                }
              - label: "CTA"
                name: "cta"
                widget: "object"
                required: false
                fields:
                  - {
                      label: Icon,
                      name: icon,
                      widget: object,
                      required: false,
                      fields: [
                        {
                          label: "Image",
                          name: "image",
                          widget: file,
                          media_library: { config: { multiple: false } },
                          hint: "SVG only. SVG must have width and height attributes set in the file."
                        },
                        {label: "Alt", name: "alt", widget: "string"}
                      ]
                    }
                  - {label: "Label", name: "label", widget: "string"}
              - {
                  label: "CTA Buttons",
                  name: "cta_buttons",
                  widget: "list",
                  allow_add: true,
                  required: false,
                  fields: [
                    { label: Label, name: label, widget: string },
                    { label: URL, name: url, widget: string },
                  ],
                }
          - label: "Team Section"
            name: "team_section"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {
                  label: "Team",
                  name: "team",
                  widget: "list",
                  allow_add: true,
                  fields:
                    [
                      {label: "Name", name: "name", widget: "string"},
                      {label: "Title", name: "title", widget: "string"},
                      {
                        label: "Profile Image",
                        name: "image",
                        widget: "image",
                        hint: "Minimum image width of 528px required (to be
                          rendered as 274px) to support higher resolution screens",
                      },
                      {
                        label: "Social Links",
                        name: "social_links",
                        widget: "list",
                        allow_add: true,
                        required: false,
                        hint: "Only Twitter, LinkedIn, GitHub or Keybase social links will be displayed",
                        fields: [{ label: URL, name: url, widget: string }],
                      },
                    ]
                }
          - label: "Advisors Section"
            name: "advisors_section"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {
                  label: "Advisors",
                  name: "advisors",
                  widget: "list",
                  allow_add: true,
                  fields:
                    [
                      {label: "Name", name: "name", widget: "string"},
                      {label: "Title", name: "title", widget: "string"},
                      {
                        label: "Profile Image",
                        name: "image",
                        widget: "image",
                        hint: "Minimum image width of 528px required (to be
                          rendered as 274px) to support higher resolution screens",
                      },
                      {
                        label: "Social Links",
                        name: "social_links",
                        widget: "list",
                        allow_add: true,
                        required: false,
                        hint: "Only Twitter, LinkedIn, GitHub or Keybase social links will be displayed",
                        fields: [{ label: URL, name: url, widget: string }],
                      },
                    ]
                }
          - label: "Supporters Section"
            name: "supporters_section"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {
                label: "Supporters",
                name: "supporters",
                widget: "list",
                allow_add: true,
                fields:
                  [
                    {label: "Name", name: "name", widget: "string"},
                    {label: "URL", name: "url", widget: "string"},
                    {
                      label: Logo,
                      name: logo,
                      widget: object,
                      fields:
                        [
                          {
                            label: Image,
                            name: image,
                            widget: image,
                            hint: "Image should be at least the 2x resolution size",
                          },
                          { label: Alt, name: alt, widget: string },
                        ],
                    }
                  ],
              }
      - file: "src/pages/press.md"
        label: "Press"
        name: "press"
        fields:
          - {
              label: "Template",
              name: "template",
              widget: "hidden",
              default: "press-page",
            }
          - {label: "Path", name: "path", widget: "hidden", default: "/press"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "markdown", minimal: true}
          - label: "Media Kit Section"
            name: "media_kit_section"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
              - label: "Media Kit"
                name: "media_kit"
                widget: "object"
                fields:
                  - {label: "Label", name: "label", widget: "string"}
                  - {label: "Contents", name: "contents", widget: "list"}
                  - {
                      label: Icon,
                      name: icon,
                      widget: object,
                      fields: [
                        {
                          label: "Image",
                          name: "image",
                          widget: file,
                          media_library: { config: { multiple: false } },
                          hint: "SVG only. SVG must have width and height attributes set in the file."
                        },
                        {label: "Alt", name: "alt", widget: "string"}
                      ]
                    }
                  - label: "Download Button"
                    name: "download_button"
                    widget: "object"
                    fields:
                      - {label: "Label", name: "label", widget: "string"}
                      - {
                        label: File,
                        name: file,
                        widget: file,
                        media_library: { config: { multiple: false } },
                        hint: "Media Kit Zip file"
                      }
          - label: "Press Items Section"
            name: "press_items_section"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Press Items"
                name: "press_items"
                widget: "list"
                allow_add: true
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Date", name: "date", widget: "datetime"}
                  - {label: "Source", name: "source", widget: "string"}
                  - {label: "Excerpt", name: "excerpt", widget: "markdown", minimal: true}
                  - {label: "URL", name: "url", widget: "string"}
      - file: "src/pages/privacy-policy.md"
        label: "Privacy Policy"
        name: "privacy_policy"
        fields:
          - {label: "Template Key", name: "template", widget: "hidden", default: "legal-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/privacy-policy"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Date Heading", name: "date", widget: "string"}
          - {label: "Introduction", name: "intro", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/california-privacy-notice.md"
        label: "California Privacy Notice"
        name: "california_privacy_notice"
        fields:
          - {label: "Template Key", name: "template", widget: "hidden", default: "legal-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/california-privacy-notice"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Date Heading", name: "date", widget: "string"}
          - {label: "Introduction", name: "intro", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/terms-of-use.md"
        label: "Terms of Use"
        name: "terms_of_use"
        fields:
          - {label: "Template Key", name: "template", widget: "hidden", default: "legal-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/terms-of-use"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Date Heading", name: "date", widget: "string"}
          - {label: "Introduction", name: "intro", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/playing-for-keeps-terms.md"
        label: "Playing for Keeps Terms"
        name: "playing_for_keeps_terms"
        fields:
          - {label: "Template Key", name: "template", widget: "hidden", default: "legal-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/terms-of-use"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Date Heading", name: "date", widget: "string"}
          - {label: "Introduction", name: "intro", widget: "markdown", required: false}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "header"
    label: "Header"
    files:
      - file: "src/header/announcement.md"
        label: "Announcement Banner"
        name: "announcement"
        fields:
          - {label: "Template Key", name: "template", widget: "hidden", default: "announcement"}
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown", required: false, minimal: true}
      - file: "src/header/nav.md"
        label: "Nav"
        name: "header_nav"
        fields:
          - {label: "Template Key", name: "template", widget: "hidden", default: "header-nav"}
          - {
            label: "Nav Items",
            name: "nav_items",
            widget: "list",
            allow_add: true,
            fields:
              [
                { label: "Label", name: "label", widget: "string" },
                {
                  label: "URL",
                  name: "url",
                  widget: "string",
                  hint: "Use a relative URL (e.g. /press or #team) if the link is an internal link.",
                },
              ],
          }
  - name: "footer"
    label: "Footer"
    files:
      - file: "src/footer/index.md"
        label: "Footer Nav"
        name: "footer_nav"
        fields:
          - {label: "Template Key", name: "template", widget: "hidden", default: "footer-nav"}
          - label: "Email Link"
            name: "email_link"
            widget: "object"
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Email Address", name: "email", widget: "string"}
          - label: "Nav Categories"
            name: "nav_categories"
            widget: "list"
            allow_add: true
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {
                label: "Items",
                name: "items",
                widget: "list",
                allow_add: true,
                fields:
                  [
                    { label: "Label", name: "label", widget: "string" },
                    {
                      label: "URL",
                      name: "url",
                      widget: "string",
                      hint: "Use a relative URL (e.g. /press or #team) if the link is an internal link.",
                    },
                  ]
                }
          - {label: "Copyright Text", name: "copyright_text", widget: "markdown", minimal: true}
          - label: "Legal Links"
            name: "legal_links"
            widget: "list"
            allow_add: true
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {
                  label: "External Link",
                  name: "is_external_link",
                  widget: "boolean",
                  default: false,
                }
              - {
                  label: "URL",
                  name: "url",
                  widget: "string",
                  hint: "Use a relative URL (e.g. /press or #team) if the link is an internal link.",
                }